### ISSUE TITLE
create an organised project structure

### ISSUE THREAD

**Issue by goelaakash79** [dsckiet/dsc-connect-backend#3]
@rhnmht30 please help @ShashankJaitly to **create a better project structure** with better code modularity and readability.

**Comment by goelaakash79** [comment]
Any updates on this?

**Comment by rhnmht30** [comment]
I'll have to check this online. I don't know the best project structure for a Django project.

**Comment by ShashankJaitly** [comment]
Sir at the I will be using automated documentation (using Swagger) that
shall solve problem of documents.

**Comment by rhnmht30** [comment]
Do you mean API documentation?

**Comment by ShashankJaitly** [comment]
Yes

**Comment by rhnmht30** [comment]
Ok! Go ahead

**Comment by goelaakash79** [comment]
Just make sure to push the organised code.
